Modificacoes no caminho dos models do pattyFW, correcao no public da …
paulohgs/dual-app pull request #9
Opened 2021-10-07 18:12 UTC by wwagner33

…aplicacao

2021-10-07 18:15 UTC, wwagner33 commented
Oi, galera. Tinha um problema no caminho do Model do pattyFW que eu vi e corrigi. Também estava estranho a declaração do PUBLIC para o Express. Tirei a referência do bodyParser que estava descontinuada. Tentai colocar duas imagens na tela principal para testar como ficariam. Quando puderem, deem uma olhada e, se estiver tudo ok, façam o merge destas correções. Valeu!

2021-10-07 23:23 UTC, paulohgs commented
Tranquilo professor, agradeço as mudanças de melhoria, eu estava tentando encontrar algum tempo para realizá-las, mas acabei não conseguindo. Vou estar testando e em seguida realizando o merge para a main!

2021-10-07 23:52 UTC, paulohgs requested changes

2021-10-07 23:52 UTC, paulohgs commented on views/partials/head.ejs
> -<link rel="stylesheet" href="../public/styles/app.css" type="text/css">
Acontece que nesse trecho precisa manter a / anterior ao styles professor, pois acontece de perder a refrência do css para a página.

2021-10-07 23:52 UTC, paulohgs commented on views/partials/head.ejs
> -<link rel="shortcut icon" href="/public/favicon.ico" type="image/x-icon">
A mesma questão da linha abaixo sobre a /.

2021-10-07 23:52 UTC, paulohgs commented on views/login.ejs
> -                            <img src="../public/images/dual-logo.svg" class="d-block" alt="logo da aplicação Dual">
Mesma questão da /.

2021-10-08 13:56 UTC, wwagner33 commented
Oi, Paulo. Pode tirar a parte de ../public/ da frente do styles/. A
aplicação já aceita sem isso. Pode confiar. 😁

Em qui, 7 de out de 2021 20:52, Paulo Henrique ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In views/partials/head.ejs
> <https://github.com/paulohgs/dual-app/pull/9#discussion_r724608228>:
>
> >  <link ***@***.***/dist/css/bootstrap.min.css" rel="stylesheet"
>
>      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
>
> -<link rel="stylesheet" href="../public/styles/app.css" type="text/css">
>
>
> Acontece que nesse trecho precisa manter a / anterior ao styles professor,
> pois acontece de perder a refrência do css para a página.
> ------------------------------
>
> In views/partials/head.ejs
> <https://github.com/paulohgs/dual-app/pull/9#discussion_r724608317>:
>
> > @@ -1,15 +1,15 @@
>
>  <meta charset="UTF-8">
>
>  <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
>  <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> -<link rel="shortcut icon" href="/public/favicon.ico" type="image/x-icon">
>
>
> A mesma questão da linha abaixo sobre a /.
> ------------------------------
>
> In views/login.ejs
> <https://github.com/paulohgs/dual-app/pull/9#discussion_r724608881>:
>
> > @@ -8,7 +8,7 @@
>
>                  <div class="col-lg-5" id="coluna1">
>
>                      <form id="formsLogin" method="POST" action="entrar">
>
>                          <div class="row mb-3">
>
> -                            <img src="../public/images/dual-logo.svg" class="d-block" alt="logo da aplicação Dual">
>
>
> Mesma questão da /.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/paulohgs/dual-app/pull/9#pullrequestreview-774487744>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC5DTCK5GGUSLV6GRREIULUFYXEPANCNFSM5FR4DT2A>
> .
>

2021-10-08 14:01 UTC, paulohgs commented
Está certo então professor, vou tá fazendo o merge em seguida!

2021-10-08 14:01 UTC, paulohgs approved these changes

2021-10-08 14:01 UTC, merged